[package]
name = "ludusavi"
version = "0.10.0"
authors = ["mtkennerly <mtkennerly@gmail.com>"]
edition = "2018"
description = "Game save backup tool"
repository = "https://github.com/mtkennerly/ludusavi"
readme = "README.md"
license = "MIT"

[dependencies]
base64 = "0.12.3"
byte-unit = "4.0.8"
copypasta = "0.7.0"
dialoguer = "0.6.2"
dirs = "3.0.0"
fuzzy-matcher = "0.3.5"
glob = "0.3.0"
iced = { version = "0.2.0", features = ["glow", "glow_default_system_font"] }
iced_native = { version = "0.3.0" }
image = { version = "0.23.7", features = ["ico"], default-features = false }
indicatif = { version = "0.15.0", features = ["rayon"] }
itertools = "0.9.0"
native-dialog = "0.4.4"
opener = "0.4.1"
rayon = "1.3.1"
reqwest = { version = "0.10.6", features = ["blocking", "rustls-tls"], default-features = false }
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.57"
serde_yaml = "0.8.13"
simple_logger = "2.1.0"
structopt = "0.3.15"
thiserror = "1.0.20"
walkdir = "2.3.1"
whoami = "0.9.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.7.0"
winapi = { version = "0.3.9", features = ["wincon"], default-features = false }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dev-dependencies]
maplit = "1.0.2"
pretty_assertions = "0.6.1"

[profile.dev]
opt-level = 3
